---
title: "R Notebook"
output: html_notebook
---

agregamos las librerias
```{r}
library(readr)
library(stringr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggthemes)
```

corremos los scripts para que sea reproducible
```{r}
source("metadata.R"  , encoding = 'UTF-8')
source("utils.R"     , encoding = 'UTF-8')
source("00-load.R"   , encoding = 'UTF-8')
```
mostramos los datos antes de modificar
```{r}
summary(autos_data)
glimpse(autos_data)
```
ahora si modificamos los datos 
```{r}
source("01-prepare.R", encoding = 'UTF-8')
autos_data[problematic_rows,]
source("02-clean.R",   encoding = 'UTF-8')
autos_data[problematic_rows,]
#imputar_por_similitud(autos_data, 10)
autos_data <- readRDS('autos_imputada_corregida.rds')
```
mostramos los datos post-modificacion
```{r}
summary(autos_data)
glimpse(autos_data)
```
## EDA univariado
```{r}
library(gridExtra)
h1 <- ggplot(autos_data, aes(price)) + geom_histogram()
h2 <- ggplot(autos_data, aes(wheel_base)) + geom_histogram()
h3 <- ggplot(autos_data, aes(curb_weight)) + geom_histogram()
h4 <- ggplot(autos_data, aes(bore)) + geom_histogram()
h5 <- ggplot(autos_data, aes(horsepower)) + geom_histogram()
h6 <- ggplot(autos_data, aes(stroke)) + geom_histogram()
grid.arrange (h1, h2, h3, h4, h5, h6, nrow=2)
```
```{r}
ggplot(autos_data, aes(price, horsepower, color=num_of_cylinders)) +
  geom_point() + 
  theme(legend.position="bottom") + 
  scale_colour_colorblind()
```
notamos una distribucion similar en price, wheel_base y horsepower. Tambien tienen una distribucion similar bore y stroke

## EDA bivariado
```{r}
library(GGally)
tipos_de_graficas(autos_data, todas=FALSE, c("symboling", "normalized_losses", "fuel_type", "aspiration", "num_of_doors", "body_style", "drive_wheels"))
                  
tipos_de_graficas(autos_data, todas=FALSE, c("engine_location", "wheel_base", "length", "width", "height", "curb_weight", "engine_type", "num_of_cylinders", "engine_size", "fuel_system", "bore", "stroke" ))

tipos_de_graficas(autos_data, todas=FALSE, c("compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price" ))
colnames(autos_data)
```

## EDA multivariado
```{r}
ggparcoord(data = autos_data, columns = c(1:26), scale="uniminmax") + 
  xlab("") + ylab("") +
  theme(axis.text.x = element_text(angle = 45))
```

